"""Java-free OWL2Vec* projection over shared pyowl-core ontology views."""

from ._version import (
    BATCH_SINK_PROTOCOL_VERSION,
    COMPILER_CACHE_SCHEMA,
    CONSUMER_CONFORMANCE_SCHEMA,
    CORE_ADAPTER_PROTOCOL_VERSION,
    CORE_API_VERSION,
    CORE_MODEL_SCHEMA_VERSION,
    CORE_WIRE_FORMAT_VERSION,
    EDGE_ARTIFACT_SCHEMA,
    INGESTION_PROVENANCE_SCHEMA,
    PROJECTOR_API_VERSION,
    REFERENCE_PROFILE,
    __version__,
)
from .api import (
    EdgeBatchSink,
    Projector,
    iter_source_edges,
    iter_taxonomy_edges,
    project_source,
    project_taxonomy,
    write_edge_artifact,
)
from .artifact import CanonicalEdgeDigest, EdgeArtifactResult
from .backend import (
    BackendSelection,
    NativeBackendStatus,
    probe_native_backend,
    select_backend,
)
from .conformance import (
    ConsumerConformanceCase,
    ConsumerConformanceResult,
    ConsumerFixture,
    IdentityProbe,
    SnapshotProviderProbe,
    canonical_edges_sha256,
    consumer_conformance_case,
    consumer_conformance_cases,
    consumer_conformance_fixture,
    consumer_conformance_fixture_metadata,
    verify_consumer_conformance,
)
from .diagnostics import DiagnosticSeverity, ProjectionDiagnostic
from .encoded import ENCODED_SCHEMA_NAME, ENCODED_SCHEMA_VERSION
from .errors import (
    ConsumerConformanceError,
    InvalidProjectionOptionsError,
    NativeBackendFallbackWarning,
    NativeBackendUnavailableError,
    ProjectionError,
    ProjectionResourceError,
    ProjectionWarning,
    SnapshotCompatibilityError,
    UnsupportedAxiomShapeError,
    UnsupportedProfileError,
)
from .model import Edge
from .options import ProjectionOptions
from .protocols import EdgeBatchSinkV1
from .provenance import (
    CoreProvenance,
    IngestionPath,
    IngestionProvenance,
    ProjectionCounts,
    ProjectionProvenance,
    ProjectionReport,
    ProjectionResult,
)
from .streaming import SpillMetrics, StreamingLimits

__all__ = [
    "BATCH_SINK_PROTOCOL_VERSION",
    "COMPILER_CACHE_SCHEMA",
    "CONSUMER_CONFORMANCE_SCHEMA",
    "CORE_ADAPTER_PROTOCOL_VERSION",
    "CORE_API_VERSION",
    "CORE_MODEL_SCHEMA_VERSION",
    "CORE_WIRE_FORMAT_VERSION",
    "EDGE_ARTIFACT_SCHEMA",
    "ENCODED_SCHEMA_NAME",
    "ENCODED_SCHEMA_VERSION",
    "INGESTION_PROVENANCE_SCHEMA",
    "PROJECTOR_API_VERSION",
    "REFERENCE_PROFILE",
    "BackendSelection",
    "CanonicalEdgeDigest",
    "ConsumerConformanceCase",
    "ConsumerConformanceError",
    "ConsumerConformanceResult",
    "ConsumerFixture",
    "CoreProvenance",
    "DiagnosticSeverity",
    "Edge",
    "EdgeArtifactResult",
    "EdgeBatchSink",
    "EdgeBatchSinkV1",
    "IdentityProbe",
    "IngestionPath",
    "IngestionProvenance",
    "InvalidProjectionOptionsError",
    "NativeBackendFallbackWarning",
    "NativeBackendStatus",
    "NativeBackendUnavailableError",
    "ProjectionCounts",
    "ProjectionDiagnostic",
    "ProjectionError",
    "ProjectionOptions",
    "ProjectionProvenance",
    "ProjectionReport",
    "ProjectionResourceError",
    "ProjectionResult",
    "ProjectionWarning",
    "Projector",
    "SnapshotCompatibilityError",
    "SnapshotProviderProbe",
    "SpillMetrics",
    "StreamingLimits",
    "UnsupportedAxiomShapeError",
    "UnsupportedProfileError",
    "__version__",
    "canonical_edges_sha256",
    "consumer_conformance_case",
    "consumer_conformance_cases",
    "consumer_conformance_fixture",
    "consumer_conformance_fixture_metadata",
    "iter_source_edges",
    "iter_taxonomy_edges",
    "probe_native_backend",
    "project_source",
    "project_taxonomy",
    "select_backend",
    "verify_consumer_conformance",
    "write_edge_artifact",
]
